version: "3.9"

services:
  dtrack-apiserver:
    image: dependencytrack/apiserver:latest
    container_name: dtrack_apiserver
    environment:
      - ALPINE_DATABASE_MODE=embedded
      - ALPINE_ENFORCE_AUTHENTICATION=true
    ports:
      - "8081:8080"
    restart: unless-stopped

  dtrack-frontend:
    image: dependencytrack/frontend:latest
    container_name: dtrack_frontend
    environment:
      - API_BASE_URL=http://localhost:8081
    ports:
      - "8080:8080"
    depends_on:
      - dtrack-apiserver
    restart: unless-stopped
